public enum MessageIDs
{
    CHAT_MSG = 1,
    PLAYER_POS_UPDATE,
    PLAYER_JOIN,
    PLAYER_SETID,
    GAME_START,
    CHANGE_ROLE,
    BOID_UPDATE,
    BOID_SPAWN,
    LEADERBOARD_UPDATE,
    ADMIN_COMMAND,
    AI_SPAWN,
    AI_UPDATE,
}